/**
 * context-ledger.ts — Durable, user-selected context that accompanies an agent
 * launch, plus the persisted graph that /ot reconstructs from session files.
 *
 * Ledger model:
 *   - Every agent launch that builds context emits a ContextLedgerNode. The
 *     node is stored ONCE, in the CHILD session's JSONL, as a pi custom entry
 *     (`olive-agent-context-ledger`). It carries snapshots (not just entry
 *     ids), so it survives compaction / branching of the source session.
 *   - The PARENT session stores a link entry (`olive-agent-context-link`) that
 *     records the child session identity + reopen descriptor + ledger ids.
 *   - Context inheritance follows `node.parentId`, NOT session nesting, so
 *     parallel children, skipped-parent children, and isolated launches all
 *     place correctly in the /ot tree.
 *   - The child's launch prompt carries the FULL inherited chain (ancestor
 *     nodes root→leaf + the new node), so a fresh agent sees its whole
 *     upstream context without re-reading any session file.
 *
 * Nothing here writes to the project workspace. Ledger persistence uses pi
 * session JSONL files only; temporary launch specs use the existing
 * /tmp/olive-agents mailbox dirs.
 */

import type { AgentMessage } from "@earendil-works/pi-ai";
import {
  type SessionEntry,
  type SessionHeader,
  parseSessionEntries,
  sessionEntryToContextMessages,
} from "@earendil-works/pi-coding-agent";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { ThinkingLevel } from "./types.js";

// ---- Entry types ---------------------------------------------------------

export const CONTEXT_LEDGER_ENTRY = "olive-agent-context-ledger";
export const CONTEXT_LINK_ENTRY = "olive-agent-context-link";

export interface LedgerMessageSnapshot {
  kind: "message";
  entryId: string;
  role: string;
  /** Short label for the TUI (role + preview). */
  label: string;
  /** Full serialized text of the message (snapshot — survives compaction). */
  text: string;
}

export type LedgerSnapshot = LedgerMessageSnapshot;

export interface ContextLedgerNode {
  version: 1;
  /** Stable ledger node id (UUID). Display numbering is computed from this. */
  id: string;
  /**
   * Id of the ledger node this context extends (the ledger the current agent
   * was launched with), or undefined when the current agent has no ledger.
   */
  parentId?: string;
  sourceSessionFile?: string;
  sourceSessionName: string;
  createdAt: string;
  /** Non-mutating compaction output (generated by the summarizer). */
  summary?: string;
  selections: LedgerSnapshot[];
}

/** Parent-session link entry payload (pi custom entry, not in LLM context). */
export interface ContextLinkData {
  version: 1;
  stage: "launching" | "ready";
  /** 17-char olive-agents manager record id. */
  agentId: string;
  agentType: string;
  description: string;
  childSessionId: string;
  childSessionName: string;
  /** Resolved JSONL path once the child reports ready. */
  childSessionFile?: string;
  /** Node id of the context passed to this child (undefined = isolated launch). */
  ledgerNodeId?: string;
  /** Node id this child's context extends (the source agent's own node). */
  parentLedgerId?: string;
  createdAt: string;
  /** Sanitized launch metadata — enough to reopen the session in a fresh window. */
  reopen?: ReopenDescriptor;
}

/** Sanitized launch descriptor persisted for /ot session reopening. */
export interface ReopenDescriptor {
  type: string;
  description: string;
  cwd: string;
  model: { provider: string; id: string };
  thinking?: ThinkingLevel;
  tools: string[];
  noExtensions: boolean;
  extensionPaths: string[];
  noSkills: boolean;
  systemPrompt?: string;
  promptPolicy?: "native" | "inherit";
  sessionDir?: string;
}

// ---- Reading custom entries from session entries -------------------------

function readCustom<T>(entries: SessionEntry[], customType: string, pick: (d: unknown) => T | undefined): T[] {
  const out: T[] = [];
  for (const entry of entries) {
    if (entry.type === "custom" && entry.customType === customType) {
      const value = pick(entry.data);
      if (value !== undefined) out.push(value);
    }
  }
  return out;
}

/** The ledger node a session received (its own `olive-agent-context-ledger` entry). */
export function getSessionLedgerNode(entries: SessionEntry[]): ContextLedgerNode | undefined {
  const nodes = readCustom<ContextLedgerNode>(entries, CONTEXT_LEDGER_ENTRY, (d) => {
    const raw = d as { node?: ContextLedgerNode } | undefined;
    return raw?.node ?? undefined;
  });
  return nodes[nodes.length - 1];
}

/** Child-session link entries stored in this session. */
export function getSessionLinks(entries: SessionEntry[]): ContextLinkData[] {
  return readCustom<ContextLinkData>(entries, CONTEXT_LINK_ENTRY, (d) => {
    const link = d as ContextLinkData | undefined;
    if (!link || typeof link !== "object") return undefined;
    return link.version === 1 ? link : undefined;
  });
}

/** A session's parent session file, from its JSONL header. */
export function headerParent(fileEntries: (SessionEntry | SessionHeader)[]): string | undefined {
  const header = fileEntries.find((e): e is SessionHeader => e.type === "session");
  return header?.parentSession;
}

// ---- Message / tool extraction from a session branch ----------------------

interface ContentBlockLike { type: string; text?: string; }

function extractText(message: AgentMessage): string {
  const content = message.content;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    const parts = content.map((block) => {
      if (typeof block === "string") return block;
      const b = block as ContentBlockLike;
      if (b.type === "text" && typeof b.text === "string") return b.text;
      if (b.type === "image") return "[image]";
      return "";
    }).filter(Boolean);
    return parts.join("\n");
  }
  return "";
}

/** First non-empty line of a string, truncated — used for TUI labels. */
export function firstLine(text: string, max = 80): string {
  const line = text.split("\n").find((l) => l.trim()) ?? "";
  const trimmed = line.trim();
  return trimmed.length > max ? `${trimmed.slice(0, max)}…` : trimmed;
}

function isToolCarrying(message: AgentMessage): boolean {
  return (
    message.role === "toolResult" ||
    message.role === "bashExecution" ||
    Array.isArray(message.content) &&
    message.content.some((block) => (block as ContentBlockLike).type === "toolResult")
  );
}

export interface SelectableMessageRow {
  entryId: string;
  role: string;
  label: string;
  preview: string;
}

/** Message rows: user/assistant/custom/compaction entries with text. Tool results are intentionally excluded (deemed noise for the ledger). */
export function selectableMessages(branch: SessionEntry[]): SelectableMessageRow[] {
  const rows: SelectableMessageRow[] = [];
  for (const entry of branch) {
    if (entry.type !== "message") continue;
    const message = entry.message;
    if (isToolCarrying(message)) continue;
    const text = extractText(message);
    if (!text.trim()) continue;
    rows.push({
      entryId: entry.id,
      role: message.role,
      label: `${message.role} · ${firstLine(text, 60)}`,
      preview: firstLine(text, 120),
    });
  }
  return rows;
}

/** Build durable snapshots from a set of selected entry ids. Tool-only entries are skipped. */
export function snapshotSelections(branch: SessionEntry[], selectedIds: Set<string>): LedgerSnapshot[] {
  const snapshots: LedgerSnapshot[] = [];
  for (const entry of branch) {
    if (!selectedIds.has(entry.id) || entry.type !== "message") continue;
    const message = entry.message;
    if (isToolCarrying(message)) continue;
    const text = extractText(message);
    if (!text.trim()) continue;
    snapshots.push({
      kind: "message",
      entryId: entry.id,
      role: message.role,
      label: `${message.role} · ${firstLine(text, 60)}`,
      text,
    });
  }
  return snapshots;
}

// ---- Markdown serialization for the child prompt ---------------------------

function snapshotMarkdown(snapshot: LedgerSnapshot): string {
  return `### ${snapshot.role} (${snapshot.entryId})\n${snapshot.text}`;
}

/** Serialize one node (summary + selected messages) to the markdown context block. */
export function nodeToMarkdown(node: ContextLedgerNode): string {
  const parts: string[] = [];
  if (node.summary?.trim()) {
    parts.push(`## Compacted context (from ${node.sourceSessionName})\n${node.summary.trim()}`);
  }
  if (node.selections.length > 0) {
    const msgs = node.selections.filter((s) => s.kind === "message");
    if (msgs.length) parts.push(`## Selected messages\n${msgs.map(snapshotMarkdown).join("\n\n")}`);
  }
  return parts.join("\n\n");
}

/**
 * Build the child's full launch prompt:
 *
 *   # context
 *   <inherited chain, root→leaf, then the new node>
 *   # instructions
 *   <agent prompt>
 */
export function buildContextPrompt(instructions: string, chain: ContextLedgerNode[], node: ContextLedgerNode): string {
  const contextNodes = [...chain, node].filter(Boolean);
  const blocks = contextNodes.map((n, i) => {
    const body = nodeToMarkdown(n);
    const header = i === contextNodes.length - 1
      ? `## Context: ${n.sourceSessionName}`
      : `## Inherited context ${i + 1}: ${n.sourceSessionName}`;
    return body ? `${header}\n${body}` : "";
  }).filter(Boolean);
  const contextBlock = blocks.length > 0 ? blocks.join("\n\n") : "(no context selected)";
  return `# context\n${contextBlock}\n\n# instructions\n${instructions}`;
}

// ---- Session file reading ------------------------------------------------

/** Parse a session JSONL file into entries (+ header). Returns [] on failure. */
export function readSessionEntries(file: string): (SessionEntry | SessionHeader)[] {
  try {
    return parseSessionEntries(readFileSync(file, "utf-8"));
  } catch {
    return [];
  }
}

/** Reduce an entry list to its plain SessionEntry components (drop header). */
export function plainEntries(all: (SessionEntry | SessionHeader)[]): SessionEntry[] {
  return all.filter((e): e is SessionEntry => e.type !== "session");
}

// ---- Ancestor resolution -------------------------------------------------

export interface AncestorSession {
  sessionFile: string;
  sessionName?: string;
  /** The ledger node this ancestor session received, if any. */
  ledgerNode?: ContextLedgerNode;
  /** This ancestor's parent session file (next hop up). */
  parentFile?: string;
}

/**
 * Resolve the ancestor chain of a session by walking JSONL header parent links
 * upward. Ordered root→leaf; the current session is the LAST element (leaf).
 * Missing/unreadable sessions stop the walk (the chain is then incomplete).
 */
export function resolveAncestorChain(currentFile: string, sessionName?: (file: string) => string | undefined): AncestorSession[] {
  const out: AncestorSession[] = [];
  const visited = new Set<string>();
  let file: string | undefined = currentFile;
  while (file && !visited.has(file)) {
    visited.add(file);
    const all = readSessionEntries(file);
    const parentFile = headerParent(all);
    const entries = plainEntries(all);
    const ledgerNode = getSessionLedgerNode(entries);
    out.unshift({ sessionFile: file, sessionName: sessionName?.(file), ledgerNode, parentFile });
    if (!parentFile) break;
    file = parentFile;
  }
  return out;
}

/**
 * The ledger node chain (root→leaf) that a launch from `currentFile` extends:
 * the current session's own node (leaf) plus its ancestors' nodes (root…).
 * Only sessions that received a ledger node contribute; isolated ancestors are
 * skipped so the chain stays contiguous in ledger ancestry terms.
 */
export function resolveLedgerChain(currentFile: string): ContextLedgerNode[] {
  const ancestors = resolveAncestorChain(currentFile);
  return ancestors.map((a) => a.ledgerNode).filter((n): n is ContextLedgerNode => Boolean(n));
}

/**
 * Nearest-first ledger ancestors of the current session, for the approval
 * "Ledger" tab and the default `parentId` of a new node. Current session's own
 * node first (leaf), then its ancestors. [] when the current agent has no
 * ledger lineage.
 */
export function resolveNearestLedgerAncestors(currentFile: string): ContextLedgerNode[] {
  return resolveLedgerChain(currentFile).reverse();
}

// ---- /ot graph -----------------------------------------------------------

export interface LedgerGraphSession {
  file: string;
  name?: string;
  parentFile?: string;
  ledgerNode?: ContextLedgerNode;
  links: ContextLinkData[];
}

export interface LedgerGraph {
  rootFile: string;
  /** All reachable sessions, keyed by file path. */
  sessions: Map<string, LedgerGraphSession>;
  /** Ledger nodes across all reachable sessions, keyed by node id. */
  nodes: Map<string, ContextLedgerNode>;
}

/**
 * Load the ledger graph around `rootFile`: the root, its descendants (via link
 * entries), AND its ancestors (via session-header parent links), so /ot can
 * re-root its view at any ancestor with `h`. `read` is injectable for tests;
 * defaults to readSessionEntries.
 */
export function loadLedgerGraph(
  rootFile: string,
  read: (file: string) => (SessionEntry | SessionHeader)[] = readSessionEntries,
  nameOf?: (file: string) => string | undefined,
): LedgerGraph {
  const sessions = new Map<string, LedgerGraphSession>();
  const nodes = new Map<string, ContextLedgerNode>();

  const visit = (file: string, viaParentHeader: boolean): void => {
    if (sessions.has(file)) return;
    const all = read(file);
    const entries = plainEntries(all);
    const node = getSessionLedgerNode(entries);
    const links = getSessionLinks(entries).filter((l) => l.stage === "ready");
    if (node) nodes.set(node.id, node);
    sessions.set(file, {
      file,
      name: nameOf?.(file),
      parentFile: viaParentHeader ? undefined : headerParent(all),
      ledgerNode: node,
      links,
    });
    // Descendants via links.
    for (const link of links) {
      if (link.childSessionFile) visit(link.childSessionFile, false);
    }
  };

  visit(rootFile, false);
  // Ancestors via session-header parent links (bounded by the visited set).
  let up = rootFile;
  while (up) {
    const all = read(up);
    const parent = headerParent(all);
    if (!parent || sessions.has(parent) || parent === up) break;
    visit(parent, true);
    up = parent;
  }
  return { rootFile, sessions, nodes };
}

// ---- Node id helpers -----------------------------------------------------

/** Generate a stable ledger node id. */
export function newLedgerNodeId(): string {
  return crypto.randomUUID();
}

// ---- Session directory fallback -------------------------------------------

/**
 * Find a session file by its session id within a session directory. Used only
 * as a recovery fallback when a link lacks a resolved child session file.
 * Returns undefined when the session cannot be found.
 */
export async function findSessionByHeaderId(
  sessionDir: string,
  cwd: string,
  sessionId: string,
): Promise<string | undefined> {
  try {
    const { SessionManager } = await import("@earendil-works/pi-coding-agent");
    const infos = await SessionManager.list(cwd, sessionDir);
    const match = infos.find((info) => info.id === sessionId);
    return match?.path;
  } catch {
    return undefined;
  }
}

// ---- Display rows (pure, testable) ----------------------------------------

export type TreeRowKind = "session" | "ledger" | "isolated";

export interface TreeRow {
  id: string;
  kind: TreeRowKind;
  label: string;
  indent: number;
  number: string;
  sessionFile?: string;
  node?: ContextLedgerNode;
  isCurrent?: boolean;
  parentFile?: string;
}

/**
 * Build display rows for /ot rooted at `viewRoot` (a session file).
 *
 * Placement follows LEDGER ancestry, not session links: a child session {
 * attaches under the session holding the ledger node its own node extends
 * (`node.parentId`); when it has no ledger node (or the parent node's session
 * is missing from the graph) it falls back to the launching session (session-
 * link parent), and finally to the root. This makes the skipped-parent case
 * (B3 launched by B2 but inheriting B1's ledger) sit level with B2 under B1.
 * Isolated children (no ledger node) render as `[isolated]` rows.
 *
 * Sibling ordering is deterministic: node createdAt+id, else link createdAt.
 */
export function computeTreeRows(
  graph: LedgerGraph,
  viewRoot: string,
  currentFile?: string,
  currentLedgerId?: string,
): TreeRow[] {
  const rows: TreeRow[] = [];
  const root = graph.sessions.get(viewRoot);
  if (!root) return rows;

  const pushSession = (s: LedgerGraphSession, indent: number, number: string): void => {
    rows.push({
      id: `session:${s.file}`,
      kind: "session",
      label: s.name ?? s.file,
      indent,
      number,
      sessionFile: s.file,
      isCurrent: s.file === currentFile,
      parentFile: s.parentFile,
    });
  };

  // Descendant-only set: sessions reachable from the view root via link
  // edges. Ancestor sessions (loaded via the header walk for `h` navigation)
  // must NEVER attach as children — treating them as attachable caused an
  // A↔main mutual-attach cycle that rendered the same nodes at every depth.
  const reachable = new Set<string>();
  {
    const stack = [viewRoot];
    while (stack.length) {
      const f = stack.pop()!;
      if (reachable.has(f)) continue;
      reachable.add(f);
      const sess = graph.sessions.get(f);
      if (!sess) continue;
      for (const link of sess.links) {
        if (link.childSessionFile) stack.push(link.childSessionFile);
      }
    }
  }

  const attachable = [...graph.sessions.values()].filter(
    (s) => s.file !== viewRoot && reachable.has(s.file),
  );

  // Holder + launcher indexes span the WHOLE graph (root, descendants, and
  // ancestors): a child's parentId may point at the view root's ledger or an
  // ancestor's ledger, and the launch fallback must find the real launcher.
  // Only the attachable set above constrains what renders as children.
  const byLedgerNodeId = new Map<string, LedgerGraphSession>();
  for (const s of graph.sessions.values()) if (s.ledgerNode) byLedgerNodeId.set(s.ledgerNode.id, s);
  const launchedBy = new Map<string, LedgerGraphSession>();
  for (const s of graph.sessions.values()) {
    for (const link of s.links) {
      if (link.childSessionFile) launchedBy.set(link.childSessionFile, s);
    }
  }

  /** The session a child attaches under (ledger parent > launching session). */
  const attachParent = (child: LedgerGraphSession): LedgerGraphSession | undefined => {
    const n = child.ledgerNode;
    if (n?.parentId) {
      const holder = byLedgerNodeId.get(n.parentId);
      if (holder) return holder;
    }
    return launchedBy.get(child.file) ?? root;
  };

  const childrenOf = (s: LedgerGraphSession): LedgerGraphSession[] => {
    const kids = attachable.filter((c) => c !== s && attachParent(c) === s);
    kids.sort((a, b) => {
      // Ledger children before isolated ones, so numbering is [1a][1b]… then [isolated].
      const pa = a.ledgerNode ? 0 : 1;
      const pb = b.ledgerNode ? 0 : 1;
      if (pa !== pb) return pa - pb;
      const aa = a.ledgerNode?.createdAt ?? "";
      const bb = b.ledgerNode?.createdAt ?? "";
      const cmp = aa.localeCompare(bb);
      if (cmp !== 0) return cmp;
      return (a.ledgerNode?.id ?? a.file).localeCompare(b.ledgerNode?.id ?? b.file);
    });
    return kids;
  };

  const walk = (s: LedgerGraphSession, depth: number): void => {
    if (depth > 32) return; // pathological cycle guard
    childrenOf(s).forEach((child, idx) => {
      if (child.ledgerNode) {
        const label = child.name ?? child.file;
        const node = child.ledgerNode;
        rows.push({
          id: `node:${node.id}`,
          kind: "ledger",
          label: `${label}${node.selections.length ? ` · ${node.selections.length} selected` : ""}`,
          indent: depth,
          number: computeNumber(depth, idx),
          sessionFile: child.file,
          node,
          isCurrent: node.id === currentLedgerId,
        });
        walk(child, depth + 1);
      } else {
        rows.push({
          id: `isolated:${child.file}`,
          kind: "isolated",
          label: child.name ?? child.file,
          indent: depth,
          number: "[isolated]",
          sessionFile: child.file,
        });
        walk(child, depth + 1);
      }
    });
  };

  pushSession(root, 0, "[0]");
  walk(root, 1);
  return rows;
}

/**
 * Display numbering: depth-1 parallel children get letters ([1a],[1b]),
 * deeper levels get plain indices ([2], [3], …).
 */
function computeNumber(depth: number, idx: number): string {
  if (depth === 1) return `[1${String.fromCharCode(97 + idx)}]`;
  return `[${depth}]`;
}
// ---- Non-mutating compaction output ---------------------------------------

export interface SummarizeRequest {
  /** Selected entries (branch order preserved). */
  branch: SessionEntry[];
  selectedIds: string[];
  model: unknown;
  thinking?: ThinkingLevel;
  customInstructions?: string;
}

export interface Summarizer {
  (request: SummarizeRequest): Promise<string>;
}

interface SummarizeAuth {
  getApiKeyAndHeaders(model: unknown): Promise<{ ok: boolean; apiKey?: string; headers?: unknown; env?: Record<string, string> }>;
}

/**
 * Non-mutating compaction output: uses pi's native compaction summarizer but
 * WITHOUT touching the session. The summary is produced from the selected
 * entries and returned; nothing is appended to any session file.
 */
export async function summarizeSelections(
  auth: SummarizeAuth,
  request: SummarizeRequest,
): Promise<string> {
  const { generateSummary } = await import("@earendil-works/pi-coding-agent");
  const model = request.model as { provider: string; id: string } | undefined;
  if (!model) throw new Error("Context summary requires the current model.");
  const resolved = await auth.getApiKeyAndHeaders(model);
  if (!resolved.ok) throw new Error(`No credentials for ${model.provider}/${model.id}`);

  const messages = request.branch
    .filter((e) => e.type === "message" && request.selectedIds.includes(e.id))
    .flatMap((e) => sessionEntryToContextMessages(e));

  const reserveTokens = 16384;
  return generateSummary(
    messages,
    model as never,
    reserveTokens,
    resolved.apiKey,
    resolved.headers as never,
    undefined,
    request.customInstructions,
    undefined,
    request.thinking as never,
    undefined,
    resolved.env,
    undefined,
    undefined,
  );
}

/** Best-effort display name for a session file (from session_info entries). */
export function sessionDisplayName(file: string): string | undefined {
  const all = readSessionEntries(file);
  for (const e of plainEntries(all)) {
    if (e.type === "session_info" && typeof e.name === "string" && e.name) return e.name;
  }
  return undefined;
}
