/**
 * context-ledger.ts — Durable, user-selected context that accompanies an agent
 * launch, plus the persisted graph that /ot reconstructs from session files.
 *
 * Ledger model:
 *   - Every agent launch that builds context emits a ContextLedgerNode. The
 *     node is stored ONCE, in the CHILD session's JSONL, as a pi custom entry
 *     (`olive-agent-context-ledger`). It carries snapshots (not just entry
 *     ids), so it survives compaction / branching of the source session.
 *   - The PARENT session stores a link entry (`olive-agent-context-link`) that
 *     records the child session identity + reopen descriptor + ledger ids.
 *   - Context inheritance follows `node.parentId`, NOT session nesting, so
 *     parallel children, skipped-parent children, and isolated launches all
 *     place correctly in the /ot tree.
 *   - The child's launch prompt carries the FULL inherited chain (ancestor
 *     nodes root→leaf + the new node), so a fresh agent sees its whole
 *     upstream context without re-reading any session file.
 *
 * Nothing here writes to the project workspace. Ledger persistence uses pi
 * session JSONL files only; temporary launch specs use the existing
 * /tmp/olive-agents mailbox dirs.
 */

import { completeSimple } from "@earendil-works/pi-ai/compat";
import { contentText, type AgentMessage, type Context, type SimpleStreamOptions, uuidv7 } from "@earendil-works/pi-ai";
import {
  convertToLlm,
  serializeConversation,
  type SessionEntry,
  type SessionHeader,
  parseSessionEntries,
  sessionEntryToContextMessages,
} from "@earendil-works/pi-coding-agent";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { ThinkingLevel } from "./types.js";

// ---- Entry types ---------------------------------------------------------

export const CONTEXT_LEDGER_ENTRY = "olive-agent-context-ledger";
export const CONTEXT_LINK_ENTRY = "olive-agent-context-link";

export interface LedgerMessageSnapshot {
  kind: "message";
  entryId: string;
  role: string;
  /** Short label for the TUI (role + preview). */
  label: string;
  /** Full serialized text of the message (snapshot — survives compaction). */
  text: string;
}

export type LedgerSnapshot = LedgerMessageSnapshot;

export interface ContextLedgerNode {
  version: 1;
  /** Stable ledger node id (UUID). Display numbering is computed from this. */
  id: string;
  /**
   * Id of the ledger node this context extends (the ledger the current agent
   * was launched with), or undefined when the current agent has no ledger.
   */
  parentId?: string;
  sourceSessionFile?: string;
  sourceSessionName: string;
  createdAt: string;
  /** Non-mutating compaction output (generated by the summarizer). */
  summary?: string;
  selections: LedgerSnapshot[];
}

/** Parent-session link entry payload (pi custom entry, not in LLM context). */
export interface ContextLinkData {
  version: 1;
  stage: "launching" | "ready";
  /** 17-char olive-agents manager record id. */
  agentId: string;
  agentType: string;
  description: string;
  childSessionId: string;
  childSessionName: string;
  /** Resolved JSONL path once the child reports ready. */
  childSessionFile?: string;
  /** Node id of the context passed to this child (undefined = isolated launch). */
  ledgerNodeId?: string;
  /** Node id this child's context extends (the source agent's own node). */
  parentLedgerId?: string;
  createdAt: string;
  /** Durable bridge used to reattach parent tracking after parent-session resume. */
  mailboxDir?: string;
  /** Original parent behavior; restored sessions notify only after explicit return. */
  isBackground?: boolean;
  /** Sanitized launch metadata — enough to reopen the session in a fresh window. */
  reopen?: ReopenDescriptor;
}

/** Sanitized launch descriptor persisted for /ot session reopening. */
export interface ReopenDescriptor {
  type: string;
  description: string;
  cwd: string;
  model: { provider: string; id: string };
  thinking?: ThinkingLevel;
  tools: string[];
  noExtensions: boolean;
  extensionPaths: string[];
  noSkills: boolean;
  systemPrompt?: string;
  promptPolicy?: "native" | "inherit";
  sessionDir?: string;
  /** Retained ceiling used when reopening an idle child session. Older links may omit it. */
  maxTurns?: number;
}

// ---- Reading custom entries from session entries -------------------------

function readCustom<T>(entries: SessionEntry[], customType: string, pick: (d: unknown) => T | undefined): T[] {
  const out: T[] = [];
  for (const entry of entries) {
    if (entry.type === "custom" && entry.customType === customType) {
      const value = pick(entry.data);
      if (value !== undefined) out.push(value);
    }
  }
  return out;
}

/** The ledger node a session received (its own `olive-agent-context-ledger` entry). */
export function getSessionLedgerNode(entries: SessionEntry[]): ContextLedgerNode | undefined {
  const nodes = readCustom<ContextLedgerNode>(entries, CONTEXT_LEDGER_ENTRY, (d) => {
    const raw = d as { node?: ContextLedgerNode } | undefined;
    return raw?.node ?? undefined;
  });
  return nodes[nodes.length - 1];
}

/** Child-session link entries stored in this session. */
export function getSessionLinks(entries: SessionEntry[]): ContextLinkData[] {
  return readCustom<ContextLinkData>(entries, CONTEXT_LINK_ENTRY, (d) => {
    const link = d as ContextLinkData | undefined;
    if (!link || typeof link !== "object") return undefined;
    return link.version === 1 ? link : undefined;
  });
}

/** A session's parent session file, from its JSONL header. */
export function headerParent(fileEntries: (SessionEntry | SessionHeader)[]): string | undefined {
  const header = fileEntries.find((e): e is SessionHeader => e.type === "session");
  return header?.parentSession;
}

// ---- Message / tool extraction from a session branch ----------------------

interface ContentBlockLike { type: string; text?: string; }

function extractText(message: AgentMessage): string {
  const content = message.content;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    const parts = content.map((block) => {
      if (typeof block === "string") return block;
      const b = block as ContentBlockLike;
      if (b.type === "text" && typeof b.text === "string") return b.text;
      if (b.type === "image") return "[image]";
      return "";
    }).filter(Boolean);
    return parts.join("\n");
  }
  return "";
}

/** First non-empty line of a string, truncated — used for TUI labels. */
export function firstLine(text: string, max = 80): string {
  const line = text.split("\n").find((l) => l.trim()) ?? "";
  const trimmed = line.trim();
  return trimmed.length > max ? `${trimmed.slice(0, max)}…` : trimmed;
}

function isToolCarrying(message: AgentMessage): boolean {
  return (
    message.role === "toolResult" ||
    message.role === "bashExecution" ||
    Array.isArray(message.content) &&
    message.content.some((block) => (block as ContentBlockLike).type === "toolResult")
  );
}

export interface SelectableMessageRow {
  entryId: string;
  role: string;
  label: string;
  preview: string;
}

/** Message rows: user/assistant/custom/compaction entries with text. Tool results are intentionally excluded (deemed noise for the ledger). */
export function selectableMessages(branch: SessionEntry[]): SelectableMessageRow[] {
  const rows: SelectableMessageRow[] = [];
  for (const entry of branch) {
    if (entry.type !== "message") continue;
    const message = entry.message;
    if (isToolCarrying(message)) continue;
    const text = extractText(message);
    if (!text.trim()) continue;
    rows.push({
      entryId: entry.id,
      role: message.role,
      label: `${message.role} · ${firstLine(text, 60)}`,
      preview: firstLine(text, 120),
    });
  }
  return rows;
}

/** Build durable snapshots from a set of selected entry ids. Tool-only entries are skipped. */
export function snapshotSelections(branch: SessionEntry[], selectedIds: Set<string>): LedgerSnapshot[] {
  const snapshots: LedgerSnapshot[] = [];
  for (const entry of branch) {
    if (!selectedIds.has(entry.id) || entry.type !== "message") continue;
    const message = entry.message;
    if (isToolCarrying(message)) continue;
    const text = extractText(message);
    if (!text.trim()) continue;
    snapshots.push({
      kind: "message",
      entryId: entry.id,
      role: message.role,
      label: `${message.role} · ${firstLine(text, 60)}`,
      text,
    });
  }
  return snapshots;
}

// ---- Markdown serialization for the child prompt ---------------------------

function snapshotMarkdown(snapshot: LedgerSnapshot): string {
  return `### ${snapshot.role} (${snapshot.entryId})\n${snapshot.text}`;
}

/** Serialize one node (summary + selected messages) to the markdown context block. */
export function nodeToMarkdown(node: ContextLedgerNode): string {
  const parts: string[] = [];
  if (node.summary?.trim()) {
    parts.push(`## Decisions from prior session\n${node.summary.trim()}`);
  }
  if (node.selections.length > 0) {
    const msgs = node.selections.filter((s) => s.kind === "message");
    if (msgs.length) parts.push(`## Selected messages\n${msgs.map(snapshotMarkdown).join("\n\n")}`);
  }
  return parts.join("\n\n");
}

/**
 * Build the child's full launch prompt:
 *
 *   # context
 *   <inherited chain, root→leaf, then the new node>
 *   # instructions
 *   <agent prompt>
 */
export function buildContextPrompt(instructions: string, chain: ContextLedgerNode[], node: ContextLedgerNode): string {
  const contextNodes = [...chain, node].filter(Boolean);
  const blocks = contextNodes.map((n, i) => {
    const body = nodeToMarkdown(n);
    const header = i === contextNodes.length - 1
      ? ""
      : `## Inherited context ${i + 1}: ${n.sourceSessionName}`;
    return body ? `${header ? `${header}\n` : ""}${body}` : "";
  }).filter(Boolean);
  const contextBlock = blocks.length > 0 ? blocks.join("\n\n") : "(no context selected)";
  return `# context\n${contextBlock}\n\n# instructions\n${instructions}`;
}

// ---- Finalization (what actually goes into the agent) ----------------------

/** Context built by the human in the approval flow, ready to finalize. */
export interface LedgerBuildInput {
  selectedIds: string[];
  summary?: string;
  /** Included parent context, ROOT→LEAF (empty = new context root). */
  inheritedNodes: ContextLedgerNode[];
}

export interface FinalizeLedgerContextInput {
  instructions: string;
  built?: LedgerBuildInput;
  /** Current session branch entries; selections are snapshotted from these. */
  branch: SessionEntry[];
  sourceSessionFile?: string;
  sourceSessionName: string;
  /** Injectable for deterministic tests; production defaults to a UUID. */
  nodeId?: string;
  /** Injectable for deterministic tests; production defaults to now. */
  createdAt?: string;
}

export interface FinalizedLedgerContext {
  prompt: string;
  ledgerNode?: ContextLedgerNode;
}

/**
 * Turn an approved context into a launch-ready ledger node + the final child
 * prompt. The prompt embeds the full inherited chain (ancestor nodes root→leaf
 * plus the new node). Returns the original instructions and no node when no
 * context was built (isolated launch). Pure: no session/ctx access.
 */
export function finalizeLedgerContext(input: FinalizeLedgerContextInput): FinalizedLedgerContext {
  const { instructions, built, branch } = input;
  if (!built) return { prompt: instructions };

  // Inherited chain is carried on the built context (root→leaf), already
  // resolved at selection time — no extra session-file reads here.
  const inherited = built.inheritedNodes ?? [];
  const parentId = inherited.length > 0 ? inherited[inherited.length - 1]!.id : undefined;
  const node: ContextLedgerNode = {
    version: 1,
    id: input.nodeId ?? newLedgerNodeId(),
    parentId,
    sourceSessionFile: input.sourceSessionFile,
    sourceSessionName: input.sourceSessionName,
    createdAt: input.createdAt ?? new Date().toISOString(),
    ...(built.summary ? { summary: built.summary } : {}),
    selections: snapshotSelections(branch, new Set(built.selectedIds)),
  };

  return { prompt: buildContextPrompt(instructions, inherited, node), ledgerNode: node };
}

// ---- Session file reading ------------------------------------------------

/** Parse a session JSONL file into entries (+ header). Returns [] on failure. */
export function readSessionEntries(file: string): (SessionEntry | SessionHeader)[] {
  try {
    return parseSessionEntries(readFileSync(file, "utf-8"));
  } catch {
    return [];
  }
}

/** Reduce an entry list to its plain SessionEntry components (drop header). */
export function plainEntries(all: (SessionEntry | SessionHeader)[]): SessionEntry[] {
  return all.filter((e): e is SessionEntry => e.type !== "session");
}

// ---- Ancestor resolution -------------------------------------------------

export interface AncestorSession {
  sessionFile: string;
  sessionName?: string;
  /** The ledger node this ancestor session received, if any. */
  ledgerNode?: ContextLedgerNode;
  /** This ancestor's parent session file (next hop up). */
  parentFile?: string;
}

/**
 * Resolve the ancestor chain of a session by walking JSONL header parent links
 * upward. Ordered root→leaf; the current session is the LAST element (leaf).
 * Missing/unreadable sessions stop the walk (the chain is then incomplete).
 */
export function resolveAncestorChain(currentFile: string, sessionName?: (file: string) => string | undefined): AncestorSession[] {
  const out: AncestorSession[] = [];
  const visited = new Set<string>();
  let file: string | undefined = currentFile;
  while (file && !visited.has(file)) {
    visited.add(file);
    const all = readSessionEntries(file);
    const parentFile = headerParent(all);
    const entries = plainEntries(all);
    const ledgerNode = getSessionLedgerNode(entries);
    out.unshift({ sessionFile: file, sessionName: sessionName?.(file), ledgerNode, parentFile });
    if (!parentFile) break;
    file = parentFile;
  }
  return out;
}

/**
 * The ledger node chain (root→leaf) that a launch from `currentFile` extends:
 * the current session's own node (leaf) plus its ancestors' nodes (root…).
 * Only sessions that received a ledger node contribute; isolated ancestors are
 * skipped so the chain stays contiguous in ledger ancestry terms.
 */
export function resolveLedgerChain(currentFile: string): ContextLedgerNode[] {
  const ancestors = resolveAncestorChain(currentFile);
  return ancestors.map((a) => a.ledgerNode).filter((n): n is ContextLedgerNode => Boolean(n));
}

/**
 * Nearest-first ledger ancestors of the current session, for the approval
 * "Ledger" tab and the default `parentId` of a new node. Current session's own
 * node first (leaf), then its ancestors. [] when the current agent has no
 * ledger lineage.
 */
export function resolveNearestLedgerAncestors(currentFile: string): ContextLedgerNode[] {
  return resolveLedgerChain(currentFile).reverse();
}

// ---- /ot graph -----------------------------------------------------------

export interface LedgerGraphSession {
  file: string;
  name?: string;
  parentFile?: string;
  ledgerNode?: ContextLedgerNode;
  links: ContextLinkData[];
}

export interface LedgerGraph {
  rootFile: string;
  /** All reachable sessions, keyed by file path. */
  sessions: Map<string, LedgerGraphSession>;
  /** Ledger nodes across all reachable sessions, keyed by node id. */
  nodes: Map<string, ContextLedgerNode>;
}

/**
 * Load the ledger graph around `rootFile`: the root, its descendants (via link
 * entries), AND its ancestors (via session-header parent links), so /ot can
 * re-root its view at any ancestor with `h`. `read` is injectable for tests;
 * defaults to readSessionEntries.
 */
export function loadLedgerGraph(
  rootFile: string,
  read: (file: string) => (SessionEntry | SessionHeader)[] = readSessionEntries,
  nameOf?: (file: string) => string | undefined,
): LedgerGraph {
  const sessions = new Map<string, LedgerGraphSession>();
  const nodes = new Map<string, ContextLedgerNode>();

  const visit = (file: string, viaParentHeader: boolean): void => {
    if (sessions.has(file)) return;
    const all = read(file);
    const entries = plainEntries(all);
    const node = getSessionLedgerNode(entries);
    const links = getSessionLinks(entries).filter((l) => l.stage === "ready");
    if (node) nodes.set(node.id, node);
    sessions.set(file, {
      file,
      name: nameOf?.(file),
      parentFile: viaParentHeader ? undefined : headerParent(all),
      ledgerNode: node,
      links,
    });
    // Descendants via links.
    for (const link of links) {
      if (link.childSessionFile) visit(link.childSessionFile, false);
    }
  };

  visit(rootFile, false);
  // Ancestors via session-header parent links (bounded by the visited set).
  let up = rootFile;
  while (up) {
    const all = read(up);
    const parent = headerParent(all);
    if (!parent || sessions.has(parent) || parent === up) break;
    visit(parent, true);
    up = parent;
  }
  return { rootFile, sessions, nodes };
}

// ---- Node id helpers -----------------------------------------------------

/** Generate a stable ledger node id. */
export function newLedgerNodeId(): string {
  return crypto.randomUUID();
}

// ---- Session directory fallback -------------------------------------------

/**
 * Find a session file by its session id within a session directory. Used only
 * as a recovery fallback when a link lacks a resolved child session file.
 * Returns undefined when the session cannot be found.
 */
export async function findSessionByHeaderId(
  sessionDir: string,
  cwd: string,
  sessionId: string,
): Promise<string | undefined> {
  try {
    const { SessionManager } = await import("@earendil-works/pi-coding-agent");
    const infos = await SessionManager.list(cwd, sessionDir);
    const match = infos.find((info) => info.id === sessionId);
    return match?.path;
  } catch {
    return undefined;
  }
}

// ---- Display rows (pure, testable) ----------------------------------------

export type TreeRowKind = "session" | "context";

export interface TreeRow {
  id: string;
  kind: TreeRowKind;
  label: string;
  indent: number;
  /** Tree connector prefix, for example `│   └── `. */
  prefix: string;
  number: string;
  sessionFile?: string;
  node?: ContextLedgerNode;
  isCurrent?: boolean;
  parentFile?: string;
}

/**
 * Build the agent tree rooted at `viewRoot`.
 *
 * A context node attaches to the session holding its parent context. A new
 * context without a parent attaches to the session that created it. Sessions
 * launched without context remain separate top-level roots, so the display
 * never implies a context relationship that does not exist.
 */
export function computeTreeRows(
  graph: LedgerGraph,
  viewRoot: string,
  currentFile?: string,
  currentLedgerId?: string,
): TreeRow[] {
  const rows: TreeRow[] = [];
  const root = graph.sessions.get(viewRoot);
  if (!root) return rows;

  const reachable = new Set<string>();
  const stack = [viewRoot];
  while (stack.length) {
    const file = stack.pop()!;
    if (reachable.has(file)) continue;
    reachable.add(file);
    for (const link of graph.sessions.get(file)?.links ?? []) {
      if (link.childSessionFile) stack.push(link.childSessionFile);
    }
  }

  const sessions = [...reachable]
    .map((file) => graph.sessions.get(file))
    .filter((session): session is LedgerGraphSession => Boolean(session));
  const byLedgerId = new Map<string, LedgerGraphSession>();
  const launchedBy = new Map<string, LedgerGraphSession>();
  for (const session of graph.sessions.values()) {
    if (session.ledgerNode) byLedgerId.set(session.ledgerNode.id, session);
    for (const link of session.links) {
      if (link.childSessionFile) launchedBy.set(link.childSessionFile, session);
    }
  }

  const attachParent = (child: LedgerGraphSession): LedgerGraphSession | undefined => {
    const node = child.ledgerNode;
    if (!node) return undefined;
    const parent = node.parentId
      ? byLedgerId.get(node.parentId)
      : node.sourceSessionFile
        ? graph.sessions.get(node.sourceSessionFile)
        : launchedBy.get(child.file); // v1 entries created before sourceSessionFile was persisted
    return parent && reachable.has(parent.file) && parent.file !== child.file ? parent : undefined;
  };

  const sortSessions = (items: LedgerGraphSession[]): LedgerGraphSession[] => items.sort((a, b) => {
    const time = (a.ledgerNode?.createdAt ?? "").localeCompare(b.ledgerNode?.createdAt ?? "");
    return time || a.file.localeCompare(b.file);
  });
  const childrenOf = (parent: LedgerGraphSession) => sortSessions(
    sessions.filter((candidate) => candidate.file !== viewRoot && attachParent(candidate)?.file === parent.file),
  );

  const forest = [
    root,
    ...sortSessions(sessions.filter((session) => session.file !== viewRoot && !attachParent(session))),
  ];
  const visited = new Set<string>();

  const walk = (
    session: LedgerGraphSession,
    depth: number,
    index: number,
    siblingCount: number,
    ancestorLast: boolean[],
  ): void => {
    if (visited.has(session.file) || depth > 32) return;
    visited.add(session.file);
    const isLast = index === siblingCount - 1;
    const prefix = depth === 0
      ? ""
      : ancestorLast.slice(1).map((last) => last ? "    " : "│   ").join("") + (isLast ? "└── " : "├── ");
    const node = session.ledgerNode;
    rows.push({
      id: node ? `context:${node.id}` : `session:${session.file}`,
      kind: node ? "context" : "session",
      label: session.name ?? session.file,
      indent: depth,
      prefix,
      number: computeNumber(depth, index, siblingCount),
      sessionFile: session.file,
      node,
      isCurrent: session.file === currentFile || node?.id === currentLedgerId,
      parentFile: session.parentFile,
    });

    const children = childrenOf(session);
    children.forEach((child, childIndex) => walk(
      child,
      depth + 1,
      childIndex,
      children.length,
      [...ancestorLast, isLast],
    ));
  };

  forest.forEach((session, index) => walk(session, 0, index, forest.length, []));
  return rows;
}

/** Letters are added only when agents are parallel at the same depth. */
function computeNumber(depth: number, index: number, siblingCount: number): string {
  return `[${depth}${siblingCount > 1 ? String.fromCharCode(97 + index) : ""}]`;
}
// ---- Non-mutating compaction output ---------------------------------------

export interface SummarizeRequest {
  /** Selected entries (branch order preserved). */
  branch: SessionEntry[];
  selectedIds: string[];
  model: unknown;
  thinking?: ThinkingLevel;
  customInstructions?: string;
}

export interface Summarizer {
  (request: SummarizeRequest): Promise<string>;
}

interface SummarizeAuth {
  getApiKeyAndHeaders(model: unknown): Promise<{ ok: boolean; apiKey?: string; headers?: unknown; env?: Record<string, string> }>;
}

const LEDGER_SUMMARIZATION_SYSTEM_PROMPT = `You are a context ledger summarization assistant. Read the supplied conversation and produce only the requested handoff context. Do not continue the conversation, answer questions from it, or imitate its formatting.`;

/** Default instructions for context sent to a fresh coding agent. */
export const DEFAULT_HANDOFF_COMPACTION_PROMPT = `Produce a compact context ledger for a coding agent that will receive the implementation plan separately. Output only a flat bullet list with no heading or sections.

Capture only prior conversation context needed to interpret and follow the plan: settled user choices; architectural decisions and how competing options were resolved; rationale, priorities, constraints, and accepted tradeoffs; and known limitations, deferrals, or excluded work, stated alongside the decision they qualify. Include current status only when it changes how the plan should be understood.

Distill the discussion into direct decision statements, such as “Auth was deferred because time to first feature mattered more.” Never narrate the conversation as “the user said” or “the assistant proposed.” Do not repeat implementation-plan details unless necessary to preserve rationale or prevent a wrong assumption. Do not invent rationale.

Do not add recommendations, next steps, TODOs, generic summaries, or a dedicated out-of-scope section. Omit transient tool output, abandoned exploration that did not affect the final direction, and implementation details already evident from the plan or code. Use concise, specific bullets, with one decision or closely related context item per bullet.`;

/**
 * Non-mutating context-ledger output. This uses a ledger-specific summarizer
 * rather than pi's native compaction wrapper because the native wrapper
 * requires a different, sectioned summary format.
 */
export async function summarizeSelections(
  auth: SummarizeAuth,
  request: SummarizeRequest,
): Promise<string> {
  const model = request.model as { provider: string; id: string; maxTokens?: number; reasoning?: boolean } | undefined;
  if (!model) throw new Error("Context summary requires the current model.");
  const resolved = await auth.getApiKeyAndHeaders(model);
  if (!resolved.ok) throw new Error(`No credentials for ${model.provider}/${model.id}`);

  const messages = request.branch
    .filter((e) => e.type === "message" && request.selectedIds.includes(e.id))
    .flatMap((e) => sessionEntryToContextMessages(e));
  const conversation = serializeConversation(convertToLlm(messages));
  const instructions = request.customInstructions?.trim() || DEFAULT_HANDOFF_COMPACTION_PROMPT;
  const context: Context = {
    systemPrompt: LEDGER_SUMMARIZATION_SYSTEM_PROMPT,
    messages: [{
      role: "user",
      content: [{
        type: "text",
        text: `<conversation>\n${conversation}\n</conversation>\n\n${instructions}`,
      }],
      timestamp: Date.now(),
    }],
  };
  const reserveTokens = 16384;
  const options: SimpleStreamOptions = {
    apiKey: resolved.apiKey,
    headers: resolved.headers as never,
    env: resolved.env,
    maxTokens: Math.min(Math.floor(0.8 * reserveTokens), model.maxTokens && model.maxTokens > 0
      ? model.maxTokens
      : Number.POSITIVE_INFINITY),
    cacheRetention: "none",
    sessionId: uuidv7(),
  };
  if (model.reasoning && request.thinking && request.thinking !== "off") {
    options.reasoning = request.thinking as SimpleStreamOptions["reasoning"];
  }
  const response = await completeSimple(model as never, context, options);
  if (response.stopReason === "error") {
    throw new Error(`Context summarization failed: ${response.errorMessage || "Unknown error"}`);
  }
  return contentText(response.content);
}

/** Best-effort display name for a session file (from session_info entries). */
export function sessionDisplayName(file: string): string | undefined {
  const all = readSessionEntries(file);
  for (const e of plainEntries(all)) {
    if (e.type === "session_info" && typeof e.name === "string" && e.name) return e.name;
  }
  return undefined;
}
